name: Keep Render Awake

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 5 minutes
  workflow_dispatch:         # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: curl -s -o /dev/null -w "%{http_code}" https://kalidsocial-7.onrender.com
